### ISSUE TITLE
Authenticated request pending

### ISSUE THREAD

**Issue by benel** [Hypertopic/AAAforREST#33]
On the production server when both LDAP and HTTP authenticators are defined on the site,
the second time a request is done to get a resource representation, the request never ends...

I didn't achieve to reproduce it on test settings yet.

**Comment by benel** [comment]
Test settings                             | Production settings
-----------------------------------------|---------------------------
Node 0.12.0                             | Node 0.10.32
local HTTP auth (couch 1.6.1) | remote HTTP auth (couch 1.5.0)
Forumsys LDAP                       | Hypertopic LDAP

**Comment by benel** [comment]
I tried (and failed) to reproduce it on Travis and locally.

It doesn't seem to be related to:
- Node version,
- remote CouchDB (for upstream and authentication),
- CouchDB version,
- LDAP configuration.

This is really puzzling...

**Comment by benel** [comment]
"Curiouser and curiouser" (as would say Alice).

On the same intranet as our servers, I tested my own laptop instead of the proxy server, using the same configuration file (just changing the `hostProxy` and the `host`): 
- it doesn't work on the server,
- it works on my laptop.

I thought about the version of `forever`. Hence I upgraded it to the last version (as on my laptop). It doesn't work better.

Any other test ideas I could do to reproduce the bug?

**Comment by franck-eyraud** [comment]
I found the origin : it is due to node not correctly closing sockets when authenticating through HTTP authenticator. I.e same issue as the one solved in 7a69c5ab : the TCP connections remain open. On my tests, after 5 opened connections, nodejs stalls before sending a new one on the same server.
It seems to depend on some system specificities, as it doesn't occur everywhere, but this makes the process use too many file descriptors as well.
